'use client'

import { useMemo, useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Heart, Menu, Minus, Plus, Search, ShoppingBag, UserRound, X } from 'lucide-react'
import { BRAND_ASSET, CUSTOM_PRODUCTS, formatPrice, PRODUCTS, type Product } from '@/lib/products'
import { ShopMenu } from '@/components/shop-menu'

const categories = ['Todos', 'Casa', 'Pequenos', 'Personalizados']
type CartLine = { product: Product; quantity: number }

export function MoorsStore() {
  const [category, setCategory] = useState('Todos')
  const [cart, setCart] = useState<Record<string, number>>({})
  const [cartOpen, setCartOpen] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const visible = useMemo(() => category === 'Todos' ? PRODUCTS : PRODUCTS.filter((p) => p.category === category), [category])
  const lines: CartLine[] = Object.entries(cart).map(([id, quantity]) => ({ product: PRODUCTS.find((p) => p.id === id)!, quantity })).filter((line) => line.product)
  const itemCount = lines.reduce((total, line) => total + line.quantity, 0)
  const subtotal = lines.reduce((total, line) => total + line.product.priceInCents * line.quantity, 0)
  function add(product: Product) { setCart((current) => ({ ...current, [product.id]: (current[product.id] || 0) + 1 })); setCartOpen(true) }
  function change(id: string, delta: number) { setCart((current) => { const next = Math.max(0, (current[id] || 0) + delta); const copy = { ...current }; if (next) copy[id] = next; else delete copy[id]; return copy }) }

  return <main className="min-h-screen bg-[#f8f4ee] text-[#302046]">
    <div className="bg-[#6d449b] px-4 py-2 text-center text-[10px] font-bold text-[#f6e9c8]">Frete grátis acima de R$ 120 <span className="mx-3 opacity-50">•</span> Até 6x sem juros</div>
    <header className="sticky top-0 z-30 border-b border-[#eadcc3] bg-[#fdfbf7]/95 backdrop-blur">
      <div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-6 lg:px-8">
        <button className="rounded-full p-2 hover:bg-[#f6e9c8] md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Abrir menu">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button>
        <Link href="#inicio" className="flex items-center gap-2 text-[#6d449b]"><span className="font-baloo text-3xl font-extrabold tracking-[-.08em]">MOORS</span><span className="hidden border-l border-[#eadcc3] pl-3 text-[10px] font-bold leading-tight text-[#927a9f] sm:block">Seu jeito de ver<br />junto com o nosso jeito de criar.</span></Link>
        <nav className={`${menuOpen ? 'absolute left-0 right-0 top-full flex' : 'hidden'} flex-col gap-1 border-b border-[#eadcc3] bg-[#fdfbf7] p-4 md:static md:flex md:flex-row md:items-center md:gap-7 md:border-0 md:bg-transparent md:p-0`}>
          <ShopMenu homeHref="/produtos" onNavigate={() => setMenuOpen(false)} />
          <a href="/personalizados" className="rounded px-3 py-2 text-xs font-extrabold uppercase tracking-wide hover:bg-[#f6e9c8]" onClick={() => setMenuOpen(false)}>Personalizados</a>
          <a href="/empresas" className="rounded px-3 py-2 text-xs font-extrabold uppercase tracking-wide hover:bg-[#f6e9c8]" onClick={() => setMenuOpen(false)}>Para empresas</a>
          <a href="#sobre" className="rounded px-3 py-2 text-xs font-extrabold uppercase tracking-wide hover:bg-[#f6e9c8]" onClick={() => setMenuOpen(false)}>Sobre a Moors</a>
        </nav>
        <div className="flex items-center gap-1 sm:gap-3"><button className="hidden rounded-full p-2 hover:bg-[#f6e9c8] sm:block" aria-label="Buscar"><Search size={18} /></button><Link href="/sign-in" className="rounded-full p-2 hover:bg-[#f6e9c8]" aria-label="Entrar"><UserRound size={18} /></Link><button className="relative rounded-full p-2 hover:bg-[#f6e9c8]" onClick={() => setCartOpen(true)} aria-label={`Carrinho com ${itemCount} itens`}><ShoppingBag size={18} />{itemCount > 0 && <span className="absolute -right-1 -top-1 flex size-4 items-center justify-center rounded-full bg-[#ff5a00] text-[9px] font-black text-white">{itemCount}</span>}</button></div>
      </div>
    </header>

    <section id="inicio" className="relative overflow-hidden bg-[#6d449b]">
      <div className="mx-auto grid max-w-7xl items-center gap-8 px-5 py-12 sm:px-8 md:grid-cols-2 md:py-20 lg:px-12"><div className="relative z-10"><p className="mb-4 text-xs font-black uppercase tracking-[.22em] text-[#f6e9c8]">Personalizados • Brindes • Presentes</p><h1 className="font-baloo max-w-xl text-6xl font-extrabold leading-[.88] tracking-[-.06em] text-[#f6e9c8] sm:text-7xl">Seu jeito de ver.<br /><span className="text-[#ff5a00]">Nosso jeito de criar.</span></h1><p className="mt-6 max-w-md text-sm leading-relaxed text-white/80 sm:text-base">Peças 3D com cor, afeto e personalidade para transformar ideias em presentes que ficam na memória.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#personalizados" className="rounded-full bg-[#ff5a00] px-5 py-3 text-xs font-black uppercase text-white transition hover:bg-[#f6e9c8] hover:text-[#6d449b]">Conheça os personalizados <ArrowRight className="ml-2 inline" size={15} /></a><a href="#categorias" className="rounded-full border border-[#f6e9c8]/60 px-5 py-3 text-xs font-black uppercase text-[#f6e9c8]">Ver coleção</a></div></div><div className="relative mx-auto aspect-square w-full max-w-md"><div className="absolute inset-6 rotate-6 rounded-[35%] bg-[#ff5a00]" /><div className="absolute inset-0 overflow-hidden rounded-[35%] border-8 border-[#f6e9c8] bg-[#f6e9c8]"><Image src="/products/mug.png" alt="Caneca 3D colorida da Moors" fill className="object-cover mix-blend-multiply" sizes="(max-width: 768px) 90vw, 45vw" /></div><span className="absolute -bottom-2 -left-2 rounded-full bg-[#f6e9c8] px-4 py-3 font-baloo text-lg font-extrabold text-[#6d449b] shadow-lg">feito para você</span></div></div>
    </section>

    <section id="categorias" className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="mb-7 flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#ff5a00]">Encontre o seu</p><h2 className="font-baloo mt-1 text-4xl font-extrabold tracking-[-.05em] text-[#6d449b]">Escolha por categoria</h2></div><a href="#produtos" className="hidden text-xs font-black uppercase text-[#6d449b] sm:block">Ver tudo <ArrowRight className="ml-1 inline" size={14} /></a></div><div className="grid gap-4 sm:grid-cols-3"><a href="#personalizados" className="group relative min-h-52 overflow-hidden rounded-2xl bg-[#ff5a00] p-6 text-white"><Image src="/products/mug.png" alt="Produtos personalizados" fill className="object-cover mix-blend-multiply opacity-60 transition duration-500 group-hover:scale-105" sizes="33vw" /><div className="relative flex h-full min-h-40 flex-col justify-end"><p className="text-xs font-bold uppercase tracking-widest text-[#f6e9c8]">Do seu jeito</p><h3 className="font-baloo text-3xl font-extrabold">Personalizados</h3><span className="mt-2 text-xs font-bold">Crie uma peça única →</span></div></a><a href="#empresas" className="group relative min-h-52 overflow-hidden rounded-2xl bg-[#f6e9c8] p-6 text-[#6d449b]"><Image src="/products/keychain.png" alt="Brindes para empresas" fill className="object-cover mix-blend-multiply opacity-55 transition duration-500 group-hover:scale-105" sizes="33vw" /><div className="relative flex h-full min-h-40 flex-col justify-end"><p className="text-xs font-bold uppercase tracking-widest text-[#ff5a00]">Para marcas</p><h3 className="font-baloo text-3xl font-extrabold">Brindes</h3><span className="mt-2 text-xs font-bold">Surpreenda seu time →</span></div></a><a href="#produtos" className="group relative min-h-52 overflow-hidden rounded-2xl bg-[#6d449b] p-6 text-[#f6e9c8]"><Image src="/products/vase.png" alt="Presentes criativos" fill className="object-cover mix-blend-screen opacity-50 transition duration-500 group-hover:scale-105" sizes="33vw" /><div className="relative flex h-full min-h-40 flex-col justify-end"><p className="text-xs font-bold uppercase tracking-widest text-[#ff5a00]">Para pessoas</p><h3 className="font-baloo text-3xl font-extrabold">Presentes</h3><span className="mt-2 text-xs font-bold">Escolha com afeto →</span></div></a></div></section>

    <section id="personalizados" className="border-y border-[#eadcc3] bg-[#f6e9c8] px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid items-center gap-10 md:grid-cols-[.9fr_1.1fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#ff5a00]">A especialidade da casa</p><h2 className="font-baloo mt-3 text-5xl font-extrabold leading-[.9] tracking-[-.06em] text-[#6d449b] sm:text-7xl">Tem uma ideia?<br />Vamos criar.</h2><p className="mt-5 max-w-md text-sm leading-relaxed text-[#6d449b]/75">Conte para a gente o que você imaginou. Desenvolvemos produtos 3D para aniversários, casamentos, marcas, eventos e tudo que merece ser só seu.</p><a href="mailto:oi@moors.com.br" className="mt-7 inline-flex items-center rounded-full bg-[#6d449b] px-5 py-3 text-xs font-black uppercase text-[#f6e9c8]">Falar sobre meu projeto <ArrowRight className="ml-2" size={15} /></a></div><div className="grid gap-3 sm:grid-cols-2">{CUSTOM_PRODUCTS.map((item) => <div key={item.title} className="relative min-h-48 overflow-hidden rounded-2xl bg-[#6d449b]"><Image src={item.image} alt={item.title} fill className="object-cover mix-blend-screen opacity-65" sizes="(max-width: 640px) 100vw, 30vw" /><div className="relative flex min-h-48 flex-col justify-end bg-gradient-to-t from-[#321d52]/80 to-transparent p-5 text-[#f6e9c8]"><p className="text-[10px] font-black uppercase tracking-widest text-[#ff5a00]">{item.label}</p><h3 className="font-baloo mt-1 text-2xl font-extrabold">{item.title}</h3><p className="mt-1 text-xs text-white/75">{item.text}</p></div></div>)}</div></div></div></section>

    <section id="produtos" className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="mb-7 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#ff5a00]">Escolhas Moors</p><h2 className="font-baloo mt-1 text-4xl font-extrabold tracking-[-.05em] text-[#6d449b]">Mais queridos</h2></div><div className="flex flex-wrap gap-2">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`rounded-full px-4 py-2 text-[10px] font-black uppercase transition ${category === item ? 'bg-[#6d449b] text-white' : 'bg-[#f6e9c8] text-[#6d449b] hover:bg-[#ff5a00] hover:text-white'}`}>{item}</button>)}</div></div><div className="grid grid-cols-2 gap-x-3 gap-y-8 md:grid-cols-3 lg:grid-cols-4">{visible.map((product) => <article key={product.id} className="group"><Link href={`/produto/${product.id}`} className="block"><div className={`relative aspect-square overflow-hidden rounded-2xl ${product.accent === 'orange' ? 'bg-[#ff5a00]' : product.accent === 'purple' ? 'bg-[#6d449b]' : 'bg-[#f6e9c8]'}`}><Image src={product.image} alt={product.name} fill className="object-cover mix-blend-multiply transition duration-500 group-hover:scale-105" sizes="(max-width: 768px) 50vw, 25vw" />{product.badge && <span className="absolute left-2 top-2 rounded-full bg-white/90 px-2 py-1 text-[9px] font-black uppercase text-[#6d449b]">{product.badge}</span>}<span className="absolute right-2 top-2 rounded-full bg-white/90 p-2 text-[#6d449b]"><Heart size={14} /></span></div><h3 className="mt-3 text-sm font-extrabold text-[#302046]">{product.name}</h3><p className="mt-1 text-[11px] text-[#927a9f]">{product.description}</p><p className="mt-2 text-sm font-black text-[#6d449b]">{formatPrice(product.priceInCents)}</p></Link><button onClick={() => add(product)} className="mt-3 w-full rounded-full bg-[#6d449b] py-2.5 text-[10px] font-black uppercase text-white transition hover:bg-[#ff5a00]">Adicionar</button></article>)}</div></section>

    <section id="empresas" className="bg-[#302046] px-4 py-12 text-center text-[#f6e9c8] sm:px-6"><p className="text-xs font-black uppercase tracking-[.2em] text-[#ff5a00]">Sua marca em cada detalhe</p><h2 className="font-baloo mx-auto mt-3 max-w-2xl text-4xl font-extrabold leading-none sm:text-6xl">Brindes que não vão parar na gaveta.</h2><p className="mx-auto mt-4 max-w-xl text-sm text-white/70">Peças criativas, úteis e com a personalidade da sua empresa. Ideal para eventos, kits de boas-vindas e ações especiais.</p><a href="mailto:oi@moors.com.br" className="mt-7 inline-flex rounded-full bg-[#ff5a00] px-6 py-3 text-xs font-black uppercase text-white">Quero brindes para minha empresa</a></section>

    <footer id="sobre" className="bg-[#6d449b] px-4 py-10 text-[#f6e9c8] sm:px-6"><div className="mx-auto flex max-w-7xl flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-baloo text-3xl font-extrabold">MOORS</p><p className="mt-1 text-xs text-white/70">Personalizados • Brindes • Presentes</p></div><p className="max-w-xs text-xs leading-relaxed text-white/70">Feito com carinho, cor e impressão 3D para deixar a vida mais parecida com você.</p></div></footer>

    {cartOpen && <div className="fixed inset-0 z-50"><button className="absolute inset-0 bg-[#101a35]/45" aria-label="Fechar carrinho" onClick={() => setCartOpen(false)} /><aside className="absolute right-0 top-0 flex h-full w-full max-w-md flex-col bg-[#fdfbf7] p-6"><div className="flex items-center justify-between border-b border-[#eadcc3] pb-4"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#ff5a00]">Seu carrinho</p><h2 className="font-baloo mt-1 text-2xl font-extrabold text-[#6d449b]">Do seu jeito</h2></div><button onClick={() => setCartOpen(false)} aria-label="Fechar carrinho"><X /></button></div><div className="flex-1 overflow-y-auto py-6">{lines.length ? <div className="flex flex-col gap-5">{lines.map(({ product, quantity }) => <div key={product.id} className="flex gap-3"><div className="relative size-16 rounded-xl bg-[#f6e9c8]"><Image src={product.image} alt="" fill className="object-cover mix-blend-multiply" sizes="64px" /></div><div className="flex-1"><p className="text-sm font-black text-[#6d449b]">{product.name}</p><p className="text-sm font-bold text-[#ff5a00]">{formatPrice(product.priceInCents)}</p><div className="mt-2 flex items-center gap-3"><button onClick={() => change(product.id, -1)} aria-label="Diminuir quantidade"><Minus size={13} /></button><span className="text-xs font-bold">{quantity}</span><button onClick={() => change(product.id, 1)} aria-label="Aumentar quantidade"><Plus size={13} /></button></div></div></div>)}</div> : <p className="py-20 text-center text-sm text-[#927a9f]">Seu carrinho está vazio.</p>}</div>{lines.length > 0 && <div className="border-t border-[#eadcc3] pt-5"><div className="flex justify-between font-black"><span>Subtotal</span><span>{formatPrice(subtotal)}</span></div><Link href="/checkout" className="mt-4 block rounded-full bg-[#ff5a00] py-3 text-center text-xs font-black uppercase text-white">Ir para checkout</Link></div>}</aside></div>}
  </main>
}
